services:
  scout:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501" # Opening the port for Streamlit access
    environment:
      - PYTHONPATH=/app/src
    tty: true
    stdin_open: true
